[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
borsh.workspace = true
solana-client = "2.2.1"
solana-program.workspace = true
solana-sdk = "2.2.1"
solana-cli-config = "2.2.1"

verifier.workspace = true
