[package]
name = "dynamic"
version.workspace = true
edition.workspace = true

[dependencies]
animals.workspace = true
utils.workspace = true
verifier.workspace = true

[build-dependencies]
pathdiff = "0.2.1"
