use crate::{
    AccountCast, BidirectionalStack, CacheStorage, CachedProofData, ExtendedProofData, ProofData,
    ProofDataDecommitment, ProofDataVerification, Scheduler, StarkCommitmentTrait,
    StarkVerifyTrait, BITS_SIZE, CACHE_SIZE, CAPACITY, COLUMN_VALUES_SIZE, DOMAINS_SIZE,
    LENGTH_SIZE, N_CONSTRAINTS, OODS_VALUES_SIZE, POSEIDON_BITS_SIZE, POWS_SIZE,
};
use felt::Felt;
use types::swiftness::global_values::{GlobalValues, InteractionElements};
use types::swiftness::stark::types::{
    cast_slice_to_struct, cast_slice_to_struct_mut, cast_struct_to_slice, cast_struct_to_slice_mut,
    StarkCommitment, StarkProof, VerifyVariables,
};

/// Simple error type for UniversalStackAccount to avoid cyclic dependencies
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UniversalStackError {
    InvalidConversion,
}

impl std::fmt::Display for UniversalStackError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UniversalStackError::InvalidConversion => write!(f, "Invalid conversion"),
        }
    }
}

impl std::error::Error for UniversalStackError {}

impl From<std::num::TryFromIntError> for UniversalStackError {
    fn from(_: std::num::TryFromIntError) -> Self {
        UniversalStackError::InvalidConversion
    }
}

/// Enum określający który verifier ma aktualnie dostęp do konta
#[derive(Debug, Clone, Copy, PartialEq, Eq, borsh::BorshSerialize, borsh::BorshDeserialize)]
#[borsh(use_discriminant = true)]
// #[repr(u8)]
#[repr(C)]
pub enum VerifierMode {
    Verifier1 = 0,
    Verifier2 = 1,
    Verifier3 = 2,
    Verifier4 = 3,
}

/// Uniwersalne konto stack z jednym buforem i enumem określającym tryb verifiera
#[derive(Debug)]
#[repr(C)]
pub struct UniversalStackAccount {
    /// Tryb verifiera - określa który verifier ma dostęp
    pub mode: VerifierMode,

    /// Indeksy dla BidirectionalStack
    pub front_index: usize,
    pub back_index: usize,

    /// Wspólny bufor dla wszystkich verifierów
    pub buffer: [u8; CAPACITY],

    /// Dane wspólne dla wszystkich verifierów
    pub proof: StarkProof,
    pub stark_commitment: StarkCommitment<InteractionElements>,

    /// Dane używane w zależności od trybu - zawsze zaalokowane, mogą być zerami
    pub autogenerated_pows: [Felt; POWS_SIZE],
    pub oods_values: [Felt; OODS_VALUES_SIZE],
    pub domains: [Felt; DOMAINS_SIZE],
    pub global_values: GlobalValues,
    pub constraint_coefficients: [Felt; N_CONSTRAINTS],
    pub column_values: [Felt; COLUMN_VALUES_SIZE],
    pub eval_composition_polynomial_bits: [Felt; BITS_SIZE],
    pub poseidon_bits: [Felt; POSEIDON_BITS_SIZE],
    pub verify_variables: VerifyVariables,
    pub cached_data: [u8; CACHE_SIZE],
}

impl Default for UniversalStackAccount {
    fn default() -> Self {
        Self {
            mode: VerifierMode::Verifier1,
            front_index: 0,
            back_index: CAPACITY,
            buffer: [0; CAPACITY],
            proof: StarkProof::default(),
            stark_commitment: StarkCommitment::default(),
            autogenerated_pows: [Felt::ZERO; POWS_SIZE],
            oods_values: [Felt::ZERO; OODS_VALUES_SIZE],
            domains: [Felt::ZERO; DOMAINS_SIZE],
            global_values: GlobalValues::default(),
            constraint_coefficients: [Felt::ZERO; N_CONSTRAINTS],
            column_values: [Felt::ZERO; COLUMN_VALUES_SIZE],
            eval_composition_polynomial_bits: [Felt::ZERO; BITS_SIZE],
            poseidon_bits: [Felt::ZERO; POSEIDON_BITS_SIZE],
            verify_variables: VerifyVariables::default(),
            cached_data: [0; CACHE_SIZE],
        }
    }
}

impl UniversalStackAccount {
    /// Create a new UniversalStackAccount for a specific verifier mode
    pub fn new(mode: VerifierMode) -> Self {
        let mut account = Self::default();
        account.mode = mode;
        account
    }

    /// Switch to a different verifier mode
    /// Note: All fields are always allocated, so we just update the mode
    pub fn switch_mode(&mut self, new_mode: VerifierMode) {
        self.mode = new_mode;
    }

    /// Get the current verifier mode
    pub fn mode(&self) -> VerifierMode {
        self.mode
    }

    /// Get the verifier type as a string
    pub fn verifier_type(&self) -> &'static str {
        match self.mode {
            VerifierMode::Verifier1 => "Verifier1",
            VerifierMode::Verifier2 => "Verifier2",
            VerifierMode::Verifier3 => "Verifier3",
            VerifierMode::Verifier4 => "Verifier4",
        }
    }
}

// Implement basic traits
impl AccountCast for UniversalStackAccount {}
impl Scheduler for UniversalStackAccount {}

// Implement BidirectionalStack trait
impl BidirectionalStack for UniversalStackAccount {
    type Error = UniversalStackError;

    fn push_front(&mut self, data: &[u8]) -> Result<(), Self::Error> {
        for byte in data {
            self.buffer[self.front_index] = *byte;
            self.front_index = self.front_index.saturating_add(1);
        }

        let data_length = data.len();
        for i in 0..LENGTH_SIZE {
            self.buffer[self.front_index] = ((data_length >> (i * 8)) & 0xFF).try_into()?;
            self.front_index = self.front_index.saturating_add(1);
        }

        Ok(())
    }

    fn push_back(&mut self, data: &[u8]) -> Result<(), Self::Error> {
        for byte in data.iter().rev() {
            self.back_index = self.back_index.saturating_sub(1);
            self.buffer[self.back_index] = *byte;
        }

        let data_length = data.len();
        for i in 0..LENGTH_SIZE {
            self.back_index = self.back_index.saturating_sub(1);
            self.buffer[self.back_index] = ((data_length >> (i * 8)) & 0xFF).try_into()?;
        }

        Ok(())
    }

    fn pop_front(&mut self) {
        let mut data_length = 0_usize;
        for _ in 0..LENGTH_SIZE {
            self.front_index = self.front_index.saturating_sub(1);
            let x: usize = self.buffer[self.front_index].into();
            data_length = (data_length << 8) | x;
        }

        self.front_index = self.front_index.saturating_sub(data_length);
    }

    fn pop_back(&mut self) {
        let mut data_length = 0_usize;
        for _ in 0..LENGTH_SIZE {
            let x: usize = self.buffer[self.back_index].into();
            data_length = (data_length << 8) | x;
            self.back_index = self.back_index.saturating_add(1);
        }

        self.back_index = self.back_index.saturating_add(data_length);
    }

    fn borrow_front(&self) -> &[u8] {
        let mut data_length = 0_usize;
        for i in 1..=LENGTH_SIZE {
            let x: usize = self.buffer[self.front_index.saturating_sub(i)].into();
            data_length = (data_length << 8) | x;
        }

        &self.buffer[self.front_index.saturating_sub(data_length + LENGTH_SIZE)
            ..self.front_index.saturating_sub(LENGTH_SIZE)]
    }

    fn borrow_back(&self) -> &[u8] {
        let mut data_length = 0_usize;
        for i in 0..LENGTH_SIZE {
            let x: usize = self.buffer[self.back_index.saturating_add(i)].into();
            data_length = (data_length << 8) | x;
        }

        &self.buffer[self.back_index.saturating_add(LENGTH_SIZE)
            ..self.back_index.saturating_add(LENGTH_SIZE + data_length)]
    }

    fn borrow_mut_front(&mut self) -> &mut [u8] {
        let mut data_length = 0_usize;
        for i in 1..=LENGTH_SIZE {
            let x: usize = self.buffer[self.front_index.saturating_sub(i)].into();
            data_length = (data_length << 8) | x;
        }

        &mut self.buffer[self.front_index.saturating_sub(data_length + LENGTH_SIZE)
            ..self.front_index.saturating_sub(LENGTH_SIZE)]
    }

    fn borrow_mut_back(&mut self) -> &mut [u8] {
        let mut data_length = 0_usize;
        for i in 0..LENGTH_SIZE {
            let x: usize = self.buffer[self.back_index.saturating_add(i)].into();
            data_length = (data_length << 8) | x;
        }

        &mut self.buffer[self.back_index.saturating_add(LENGTH_SIZE)
            ..self.back_index.saturating_add(LENGTH_SIZE + data_length)]
    }

    fn is_empty_front(&self) -> bool {
        self.front_index == 0
    }

    fn is_empty_back(&self) -> bool {
        self.back_index == CAPACITY
    }
}

// Implement StarkCommitmentTrait
impl StarkCommitmentTrait for UniversalStackAccount {
    fn get_stark_commitment<T: Sized>(&self) -> &T {
        let bytes = cast_struct_to_slice(&self.stark_commitment);
        assert_eq!(bytes.len(), std::mem::size_of::<T>());
        unsafe { &*(bytes.as_ptr() as *const T) }
    }

    fn get_stark_commitment_mut<T: Sized>(&mut self) -> &mut T {
        let bytes = cast_struct_to_slice_mut(&mut self.stark_commitment);
        assert_eq!(bytes.len(), std::mem::size_of::<T>());
        unsafe { &mut *(bytes.as_mut_ptr() as *mut T) }
    }

    fn set_stark_commitment<T: Sized>(&mut self, stark_commitment: &T) {
        let bytes = unsafe {
            std::slice::from_raw_parts(
                (stark_commitment as *const T) as *const u8,
                std::mem::size_of::<T>(),
            )
        };
        assert_eq!(
            bytes.len(),
            std::mem::size_of::<StarkCommitment<InteractionElements>>()
        );
        self.stark_commitment = unsafe {
            std::ptr::read(bytes.as_ptr() as *const StarkCommitment<InteractionElements>)
        };
    }
}

// Implement ProofData
impl ProofData for UniversalStackAccount {
    fn get_proof_bytes(&self) -> &[u8] {
        cast_struct_to_slice(&self.proof)
    }

    fn get_proof_bytes_mut(&mut self) -> &mut [u8] {
        cast_struct_to_slice_mut(&mut self.proof)
    }
}

// Implement ExtendedProofData - używane przez Verifier1
impl ExtendedProofData for UniversalStackAccount {
    fn get_autogenerated_pows(&self) -> &[Felt; POWS_SIZE] {
        &self.autogenerated_pows
    }

    fn get_autogenerated_pows_mut(&mut self) -> &mut [Felt; POWS_SIZE] {
        &mut self.autogenerated_pows
    }

    fn get_pows_and_domains_mut(&mut self) -> (&[Felt; POWS_SIZE], &mut [Felt; DOMAINS_SIZE]) {
        (&self.autogenerated_pows, &mut self.domains)
    }

    fn get_global_values(&self) -> &GlobalValues {
        &self.global_values
    }

    fn set_global_values(&mut self, global_values: GlobalValues) {
        self.global_values = global_values;
    }
}

// Implement StarkVerifyTrait - używane przez Verifier2 i Verifier4
impl StarkVerifyTrait for UniversalStackAccount {
    fn get_verify_variables<T: Sized>(&self) -> &T {
        let bytes = cast_struct_to_slice(&self.verify_variables);
        assert_eq!(bytes.len(), std::mem::size_of::<T>());
        unsafe { &*(bytes.as_ptr() as *const T) }
    }

    fn get_verify_variables_mut<T: Sized>(&mut self) -> &mut T {
        let bytes = cast_struct_to_slice_mut(&mut self.verify_variables);
        assert_eq!(bytes.len(), std::mem::size_of::<T>());
        unsafe { &mut *(bytes.as_mut_ptr() as *mut T) }
    }

    fn set_verify_variables<T: Sized>(&mut self, verify_variables: &T) {
        let bytes = unsafe {
            std::slice::from_raw_parts(
                (verify_variables as *const T) as *const u8,
                std::mem::size_of::<T>(),
            )
        };
        assert_eq!(bytes.len(), std::mem::size_of::<VerifyVariables>());
        self.verify_variables = unsafe { std::ptr::read(bytes.as_ptr() as *const VerifyVariables) };
    }
}

// Implement ProofDataDecommitment - używane przez Verifier1 i Verifier2
impl ProofDataDecommitment for UniversalStackAccount {
    fn get_proof_data_references<T: Sized>(
        &mut self,
    ) -> (
        &[Felt; DOMAINS_SIZE],
        &[Felt; OODS_VALUES_SIZE],
        &GlobalValues,
        &[Felt; N_CONSTRAINTS],
        &mut [Felt; BITS_SIZE],
        &mut [Felt; POSEIDON_BITS_SIZE],
    ) {
        (
            &self.domains,
            &mut self.oods_values,
            &mut self.global_values,
            &mut self.constraint_coefficients,
            &mut self.eval_composition_polynomial_bits,
            &mut self.poseidon_bits,
        )
    }

    fn get_stark_commitment_and_proof<T: Sized, P: Sized>(&self) -> (&T, &P) {
        let stark_commitment_bytes = cast_struct_to_slice(&self.stark_commitment);
        let proof_bytes = cast_struct_to_slice(&self.proof);

        assert_eq!(stark_commitment_bytes.len(), std::mem::size_of::<T>());
        assert_eq!(proof_bytes.len(), std::mem::size_of::<P>());

        let stark_commitment = unsafe { &*(stark_commitment_bytes.as_ptr() as *const T) };
        let proof = unsafe { &*(proof_bytes.as_ptr() as *const P) };

        (stark_commitment, proof)
    }

    fn get_stark_commitment_and_proof_mut<T: Sized, P: Sized>(&mut self) -> (&mut T, &mut P) {
        let stark_commitment_bytes = cast_struct_to_slice_mut(&mut self.stark_commitment);
        let proof_bytes = cast_struct_to_slice_mut(&mut self.proof);

        assert_eq!(stark_commitment_bytes.len(), std::mem::size_of::<T>());
        assert_eq!(proof_bytes.len(), std::mem::size_of::<P>());

        let stark_commitment = unsafe { &mut *(stark_commitment_bytes.as_mut_ptr() as *mut T) };
        let proof = unsafe { &mut *(proof_bytes.as_mut_ptr() as *mut P) };

        (stark_commitment, proof)
    }

    fn get_constraint_coefficients(&self) -> &[Felt; N_CONSTRAINTS] {
        &self.constraint_coefficients
    }

    fn get_constraint_coefficients_mut(&mut self) -> &mut [Felt; N_CONSTRAINTS] {
        &mut self.constraint_coefficients
    }

    fn set_constraint_coefficients(&mut self, coefficients: &[Felt]) {
        assert_eq!(coefficients.len(), N_CONSTRAINTS);
        self.constraint_coefficients.copy_from_slice(coefficients);
    }
}

// Implement ProofDataVerification - używane przez Verifier3 i Verifier4
impl ProofDataVerification for UniversalStackAccount {
    fn get_proof_data_references<T: Sized>(
        &mut self,
    ) -> (
        &[Felt; POWS_SIZE],
        &mut [Felt; OODS_VALUES_SIZE],
        &mut [Felt; N_CONSTRAINTS],
        &mut [Felt; COLUMN_VALUES_SIZE],
    ) {
        (
            &self.autogenerated_pows,
            &mut self.oods_values,
            &mut self.constraint_coefficients,
            &mut self.column_values,
        )
    }

    fn get_stark_commitment_and_proof<T: Sized, P: Sized>(&self) -> (&T, &P) {
        let stark_commitment_bytes = cast_struct_to_slice(&self.stark_commitment);
        let proof_bytes = cast_struct_to_slice(&self.proof);

        assert_eq!(stark_commitment_bytes.len(), std::mem::size_of::<T>());
        assert_eq!(proof_bytes.len(), std::mem::size_of::<P>());

        let stark_commitment = unsafe { &*(stark_commitment_bytes.as_ptr() as *const T) };
        let proof = unsafe { &*(proof_bytes.as_ptr() as *const P) };

        (stark_commitment, proof)
    }

    fn get_stark_commitment_and_proof_mut<T: Sized, P: Sized>(&mut self) -> (&mut T, &mut P) {
        let stark_commitment_bytes = cast_struct_to_slice_mut(&mut self.stark_commitment);
        let proof_bytes = cast_struct_to_slice_mut(&mut self.proof);

        assert_eq!(stark_commitment_bytes.len(), std::mem::size_of::<T>());
        assert_eq!(proof_bytes.len(), std::mem::size_of::<P>());

        let stark_commitment = unsafe { &mut *(stark_commitment_bytes.as_mut_ptr() as *mut T) };
        let proof = unsafe { &mut *(proof_bytes.as_mut_ptr() as *mut P) };

        (stark_commitment, proof)
    }

    fn get_constraint_coefficients(&self) -> &[Felt; N_CONSTRAINTS] {
        &self.constraint_coefficients
    }

    fn get_constraint_coefficients_mut(&mut self) -> &mut [Felt; N_CONSTRAINTS] {
        &mut self.constraint_coefficients
    }

    fn set_constraint_coefficients(&mut self, coefficients: &[Felt]) {
        assert_eq!(coefficients.len(), N_CONSTRAINTS);
        self.constraint_coefficients.copy_from_slice(coefficients);
    }

    fn get_stark_commitment_and_coefficients_mut<T: Sized>(
        &mut self,
    ) -> (&T, &mut [Felt; N_CONSTRAINTS]) {
        let stark_commitment_bytes = cast_struct_to_slice(&self.stark_commitment);
        assert_eq!(stark_commitment_bytes.len(), std::mem::size_of::<T>());
        let stark_commitment = unsafe { &*(stark_commitment_bytes.as_ptr() as *const T) };
        (&*stark_commitment, &mut self.constraint_coefficients)
    }
}

// // Implement CachedProofData - używane przez Verifier3 i Verifier4
impl CachedProofData for UniversalStackAccount {
    fn get_stark_commitment_proof_and_cache<T: Sized, P: Sized, C: Sized>(&self) -> (&T, &P, &C) {
        let stark_commitment_bytes = cast_struct_to_slice(&self.stark_commitment);
        let proof_bytes = cast_struct_to_slice(&self.proof);

        let cache_size = std::mem::size_of::<C>();
        let cache_bytes = &self.cached_data[..cache_size];

        assert_eq!(stark_commitment_bytes.len(), std::mem::size_of::<T>());
        assert_eq!(proof_bytes.len(), std::mem::size_of::<P>());
        assert_eq!(cache_bytes.len(), std::mem::size_of::<C>());

        let stark_commitment = unsafe { &*(stark_commitment_bytes.as_ptr() as *const T) };
        let proof = unsafe { &*(proof_bytes.as_ptr() as *const P) };
        let cache = unsafe { &*(cache_bytes.as_ptr() as *const C) };

        (stark_commitment, proof, cache)
    }

    fn get_stark_commitment_proof_and_cache_mut<T: Sized, P: Sized, C: Sized>(
        &mut self,
    ) -> (&mut T, &mut P, &mut C) {
        let stark_commitment_bytes = cast_struct_to_slice_mut(&mut self.stark_commitment);
        let proof_bytes = cast_struct_to_slice_mut(&mut self.proof);

        let cache_size = std::mem::size_of::<C>();
        let cache_bytes = &mut self.cached_data[..cache_size];

        assert_eq!(stark_commitment_bytes.len(), std::mem::size_of::<T>());
        assert_eq!(proof_bytes.len(), std::mem::size_of::<P>());
        assert_eq!(cache_bytes.len(), std::mem::size_of::<C>());

        let stark_commitment = unsafe { &mut *(stark_commitment_bytes.as_mut_ptr() as *mut T) };
        let proof = unsafe { &mut *(proof_bytes.as_mut_ptr() as *mut P) };
        let cache = unsafe { &mut *(cache_bytes.as_mut_ptr() as *mut C) };

        (stark_commitment, proof, cache)
    }
}

impl CacheStorage for UniversalStackAccount {
    fn store_in_cache<T>(&mut self, data: &T) {
        let bytes = cast_struct_to_slice(data);
        assert!(bytes.len() <= CACHE_SIZE, "Data too large for cache");
        self.cached_data[..bytes.len()].copy_from_slice(bytes);
    }

    fn borrow_from_cache<T>(&self) -> &T {
        let size = std::mem::size_of::<T>();
        cast_slice_to_struct::<T>(&self.cached_data[..size])
    }

    fn borrow_from_cache_mut<T>(&mut self) -> &mut T {
        let size = std::mem::size_of::<T>();
        cast_slice_to_struct_mut::<T>(&mut self.cached_data[..size])
    }
}
