[workspace]
resolver = "2"
members = ["client", "programs/*", "tasks/*", "parser"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
borsh = "1.5.7"
solana-program = "2.2.1"
solana-system-interface = { version = "1.0.0", features = ["bincode"] }
thiserror = "2.0.12"
typetag = "0.2.20"
lambdaworks-math = "0.12.0"
num-bigint = "0.4.6"
size-of = "0.1.5"
sha3 = { version = "0.10.8", default-features = false }

client = { path = "./client" }

verifier-2 = { path = "./programs/verifier2" }
verifier-1 = { path = "./programs/verifier1" }
verifier-3 = { path = "./programs/verifier3" }

utils = { path = "./programs/utils" }


felt = { path = "./tasks/felt" }
types = { path = "./tasks/types" }
validate-public-input = { path = "./tasks/validate_public_input" }
poseidon = { path = "./tasks/poseidon" }
pedersen = { path = "./tasks/pedersen" }
get-hash = { path = "./tasks/get_hash" }
stark-verify-decommitments = { path = "./tasks/stark_verify_decommitments" }
stark-verify-verification = { path = "./tasks/stark_verify_verification" }
stark-commit = { path = "./tasks/stark_commit" }
verify-public-input = { path = "./tasks/verify_public_input" }
verify-1 = { path = "./tasks/verify_1" }
verify-2 = { path = "./tasks/verify_2" }
verify-3 = { path = "./tasks/verify_3" }
transcript = { path = "./tasks/transcript" }