[workspace]
resolver = "2"
members = ["verifier"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
borsh = "1.5.7"
solana-program = "2.2.1"

verifier = { path = "./verifier" }
