[workspace]
resolver = "2"
members = ["verifier", "client"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
borsh = "1.5.7"
solana-program = "2.2.1"
thiserror = "2.0.12"

verifier = { path = "./verifier" }
