use crate::funvec::{FunVec, FUNVEC_AUTHENTICATIONS};
use crate::swiftness::commitment::vector::config::{Config, VectorConfigBytes};
use felt::Felt;

// Commitment for a vector of field elements.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
#[repr(C)]
pub struct Commitment {
    pub config: Config,
    pub commitment_hash: Felt,
}

#[derive(Debug, Clone, PartialEq, Default)]
#[repr(C)]
pub struct VectorCommitmentBytes {
    pub config: VectorConfigBytes,
    pub commitment_hash: [u8; 32],
}

impl Commitment {
    pub fn new(config: Config, commitment_hash: Felt) -> Self {
        Self {
            config,
            commitment_hash,
        }
    }
}

#[derive(Debug, Default, Clone, Copy, PartialEq)]
#[repr(C)]
pub struct Witness {
    // The authentication values: all the siblings of the subtree generated by the queried indices,
    // bottom layer up, left to right.
    pub authentications: FunVec<Felt, FUNVEC_AUTHENTICATIONS>,
}

// Query represents a single query to the vector commitment
#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct Query {
    pub index: Felt,
    pub value: Felt,
}

impl Query {
    pub fn new(index: Felt, value: Felt) -> Self {
        Self { index, value }
    }
}

impl Default for Query {
    fn default() -> Self {
        Self {
            index: Felt::ZERO,
            value: Felt::ZERO,
        }
    }
}

impl Query {
    pub fn from_bytes(index_bytes: &[u8], value_bytes: &[u8]) -> Self {
        Self {
            index: Felt::from_bytes_be_slice(index_bytes),
            value: Felt::from_bytes_be_slice(value_bytes),
        }
    }
    pub fn to_bytes(&self) -> (Vec<u8>, Vec<u8>) {
        (
            self.index.to_bytes_be().to_vec(),
            self.value.to_bytes_be().to_vec(),
        )
    }
}

// QueryWithDepth extends Query with depth information for tree traversal
#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(C)]
pub struct QueryWithDepth {
    pub index: Felt,
    pub value: Felt,
    pub depth: Felt,
}

impl Default for QueryWithDepth {
    fn default() -> Self {
        Self {
            index: Felt::ZERO,
            value: Felt::ZERO,
            depth: Felt::ZERO,
        }
    }
}
impl QueryWithDepth {
    pub fn from_query(query: &Query, depth: Felt) -> Self {
        Self {
            index: query.index,
            value: query.value,
            depth,
        }
    }
    pub fn from_query_with_shift(query: &Query, depth: Felt, shift: Felt) -> Self {
        Self {
            index: query.index + shift,
            value: query.value,
            depth,
        }
    }
}

#[derive(Debug, Clone)]
#[repr(C)]
pub struct PendingHashComputation {
    pub is_active: bool,
    pub parent_index: Felt,
    pub parent_depth: Felt,
    pub next_start: u128,
    pub next_auth_start: u128,
}
