[package]
name = "scheduler"
version.workspace = true
edition.workspace = true

[dependencies]
ciborium.workspace = true
serde.workspace = true
serde_with.workspace = true
thiserror.workspace = true
typetag.workspace = true
