[package]
name = "verifier"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
ciborium.workspace = true
serde.workspace = true
solana-program.workspace = true
thiserror.workspace = true
typetag.workspace = true

utils.workspace = true
