use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src");

    // Get the current crate name from Cargo.toml
    let current_crate_name = env::var("CARGO_PKG_NAME").unwrap_or_else(|_| "unknown".to_string());

    // Get the out directory for generated code
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let out_filename = format!("{}_executable_dispatch.rs", current_crate_name);
    let out_path = Path::new(&out_dir).join(out_filename);

    // Generate minimal dispatch code that does nothing
    // The universal_verifier doesn't execute tasks directly - it delegates via CPI
    let dispatch_code = r#"// AUTO-GENERATED by build.rs
// Universal verifier doesn't have its own tasks - it delegates to verifier_1-4 via CPI

pub fn execute<S>(_stack: &mut S) -> (Vec<Vec<u8>>, bool)
where
    S: utils::BidirectionalStack,
{
    // This should never be called - universal_verifier uses CPI instead
    panic!("Universal verifier should not execute tasks directly");
}
"#;

    let mut file = fs::File::create(&out_path).unwrap();
    file.write_all(dispatch_code.as_bytes()).unwrap();

    println!("cargo:warning=Generated minimal dispatch code for universal_verifier");
}
