use client::{
    initialize_client, interact_with_program_instructions, send_and_confirm_transactions,
    setup_payer, setup_program, ClientError, Config,
};
use solana_sdk::{
    compute_budget::ComputeBudgetInstruction,
    instruction::{AccountMeta, Instruction},
    signature::{Keypair, Signer},
    transaction::Transaction,
};
use solana_system_interface::instruction::create_account;
use stark::{swiftness::stark::types::StarkCommitment};
use stark::{stark_proof::verify::Verify, swiftness::stark::types::cast_struct_to_slice};
use std::{mem::size_of, path::Path};
use swiftness_proof_parser::{json_parser, transform::TransformTo, StarkProof as StarkProofParser};
use utils::{
    global_values::{GlobalValues, InteractionElements},
    AccountCast, Executable,
};
use verifier::{instruction::VerifierInstruction, state::BidirectionalStackAccount};

pub const CHUNK_SIZE: usize = 1000;

#[tokio::main]
#[allow(clippy::result_large_err)]
async fn main() -> client::Result<()> {
    env_logger::Builder::from_default_env().init();

    let config = Config::parse_args();

    let client = initialize_client(&config).await?;

    let payer = setup_payer(&client, &config).await?;

    let program_path = Path::new("target/deploy/verifier.so");

    let program_id = setup_program(&client, &payer, &config, program_path).await?;

    println!("Using program ID: {program_id}");

    let stack_account = Keypair::new();
    println!("Creating new account: {}", stack_account.pubkey());

    let space = size_of::<BidirectionalStackAccount>();
    println!("Account space: {space} bytes");

    let create_account_ix = create_account(
        &payer.pubkey(),
        &stack_account.pubkey(),
        client.get_minimum_balance_for_rent_exemption(space).await?,
        space as u64,
        &program_id,
    );

    let create_account_tx = Transaction::new_signed_with_payer(
        &[create_account_ix],
        Some(&payer.pubkey()),
        &[&payer, &stack_account],
        client.get_latest_blockhash().await?,
    );

    let signature = client
        .send_and_confirm_transaction(&create_account_tx)
        .await?;
    println!("Account created successfully: {signature}");
    println!("========================");

    let input = include_str!("../../example_proof/saya.json");
    let proof_json = serde_json::from_str::<json_parser::StarkProof>(input).unwrap();
    let proof = StarkProofParser::try_from(proof_json).unwrap();

    let mut proof_verifier = proof.transform_to();

    let proof_bytes = cast_struct_to_slice(&mut proof_verifier).to_vec();
    let proof_size = proof_bytes.len();
    let global_values_size = std::mem::size_of::<GlobalValues>();
    let stark_commitment_size = std::mem::size_of::<StarkCommitment<InteractionElements>>();

    println!("Memory layout calculation:");
    println!("  Proof size: {} bytes", proof_size);
    println!("  Global values size: {} bytes", global_values_size);
    println!("  Stark commitment size: {} bytes", stark_commitment_size);

    // Calculate offsets for each section in the account
    let stack_offset = 0; // Start of account
    let proof_offset = 16; // After front_index (8) + back_index (8)
    let buffer_offset = proof_offset + proof_size; // After proof data
    let autogenerated_pows_offset = buffer_offset + 65536; // After buffer (CAPACITY = 65536)
    let oods_values_offset = autogenerated_pows_offset + 4288; // After autogenerated_pows (POWS_SIZE * 32 = 134 * 32)
    let domains_offset = oods_values_offset + 6208; // After oods_values (OODS_VALUES_SIZE * 32 = 194 * 32)
    let global_values_offset = domains_offset + 992; // After domains (DOMAINS_SIZE * 32 = 31 * 32)
    let constraint_coefficients_offset = global_values_offset + global_values_size; // After global_values
    let column_values_offset = constraint_coefficients_offset + 6208; // After constraint_coefficients (N_CONSTRAINTS * 32 = 194 * 32)
    let stark_commitment_offset = column_values_offset + 320; // After column_values (COLUMN_VALUES_SIZE * 32 = 10 * 32)

    println!(
        "  Total account size: {} bytes",
        stark_commitment_offset + stark_commitment_size
    );
    println!("  Preallocated space breakdown:");
    println!("    Stack indices: {} bytes", proof_offset - stack_offset);
    println!("    Proof data: {} bytes", proof_size);
    println!("    Buffer: {} bytes", 65536);
    println!("    Autogenerated powers: {} bytes", 4288);
    println!("    OODS values: {} bytes", 6208);
    println!("    Domains: {} bytes", 992);
    println!("    Global values: {} bytes", global_values_size);
    println!("    Constraint coefficients: {} bytes", 6208);
    println!("    Column values: {} bytes", 320);
    println!("    Stark commitment: {} bytes", stark_commitment_size);

    // Start with stack initialization
    let mut stack_init_input: [u64; 2] = [0, 65536];
    let stack_init_bytes = cast_struct_to_slice(&mut stack_init_input);

    // Create instructions for each section
    let mut instructions = Vec::new();

    // 1. Initialize stack indices (front_index = 0, back_index = 65536)
    let stack_ix = Instruction::new_with_borsh(
        program_id,
        &VerifierInstruction::SetAccountData(stack_offset, stack_init_bytes.to_vec()),
        vec![AccountMeta::new(stack_account.pubkey(), false)],
    );
    instructions.push(stack_ix);

    // 2. Set OODS values from proof data (194 * 32 = 6208 bytes) - these are precomputed values needed for verification
    let oods_values = proof_verifier.unsent_commitment.oods_values.clone();
    let oods_values_bytes = cast_struct_to_slice(&mut oods_values.clone()).to_vec();
    let oods_values_chunks: Vec<_> = oods_values_bytes
        .chunks(CHUNK_SIZE)
        .enumerate()
        .map(|(i, chunk)| {
            Instruction::new_with_borsh(
                program_id,
                &VerifierInstruction::SetAccountData(
                    oods_values_offset + (i * CHUNK_SIZE),
                    chunk.to_vec(),
                ),
                vec![AccountMeta::new(stack_account.pubkey(), false)],
            )
        })
        .collect();
    instructions.extend(oods_values_chunks);

    // 3. Set proof data - the actual STARK proof that will be verified
    let proof_bytes = cast_struct_to_slice(&mut proof_verifier).to_vec();
    let proof_chunks: Vec<_> = proof_bytes
        .chunks(CHUNK_SIZE)
        .enumerate()
        .map(|(i, chunk)| {
            Instruction::new_with_borsh(
                program_id,
                &VerifierInstruction::SetAccountData(
                    proof_offset + (i * CHUNK_SIZE),
                    chunk.to_vec(),
                ),
                vec![AccountMeta::new(stack_account.pubkey(), false)],
            )
        })
        .collect();

    instructions.extend(proof_chunks);

    let mut transactions = Vec::new();
    for instruction in instructions.iter() {
        let set_proof_tx = Transaction::new_signed_with_payer(
            &[instruction.clone()],
            Some(&payer.pubkey()),
            &[&payer],
            client.get_latest_blockhash().await?,
        );
        transactions.push(set_proof_tx.clone());
    }
    send_and_confirm_transactions(&client, &transactions).await?;

    let verify_task = Verify::new();

    println!("Using Verify with TYPE_TAG: {}", Verify::TYPE_TAG);

    let push_task_ix = Instruction::new_with_borsh(
        program_id,
        &VerifierInstruction::PushTask(verify_task.to_vec_with_type_tag()),
        vec![AccountMeta::new(stack_account.pubkey(), false)],
    );

    let _ = interact_with_program_instructions(
        &client,
        &payer,
        &program_id,
        &stack_account,
        &[push_task_ix],
    )
    .await?;

    let mut account_data = client
        .get_account_data(&stack_account.pubkey())
        .await
        .map_err(ClientError::SolanaClientError)?;

    let stack = BidirectionalStackAccount::cast_mut(&mut account_data);
    let simulation_steps = stack.simulate();
    println!("Steps in simulation: {simulation_steps}");

    let limit_instructions = ComputeBudgetInstruction::set_compute_unit_limit(1_200_000);

    // Execute all steps until task is complete - split into chunks of max 5000
    const MAX_CHUNK_SIZE: usize = 5000;

    let simulation_steps_usize = simulation_steps as usize;

    for chunk_start in (0..simulation_steps_usize).step_by(MAX_CHUNK_SIZE) {
        let chunk_end = std::cmp::min(chunk_start + MAX_CHUNK_SIZE, simulation_steps_usize);
        let chunk_size = chunk_end - chunk_start;

        println!(
            "Processing steps {}-{} ({} steps)",
            chunk_start,
            chunk_end - 1,
            chunk_size
        );

        let mut transactions = Vec::new();
        for i in chunk_start..chunk_end {
            let execute_ix = Instruction::new_with_borsh(
                program_id,
                &VerifierInstruction::Execute(i as u32),
                vec![AccountMeta::new(stack_account.pubkey(), false)],
            );
            let execute_tx = Transaction::new_signed_with_payer(
                &[limit_instructions.clone(), execute_ix],
                Some(&payer.pubkey()),
                &[&payer],
                client.get_latest_blockhash().await?,
            );
            transactions.push(execute_tx.clone());
        }

        send_and_confirm_transactions(&client, &transactions).await?;
        println!("Chunk {}-{} completed", chunk_start, chunk_end - 1);
    }

    println!("All execution steps completed");

    Ok(())
}
