name: Solana

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev build-essential pkg-config llvm libclang-dev protobuf-compiler libssl-dev

      - name: Install Solana CLI
        run: sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"

        
      - name: Add Solana to PATH
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Build SBF program
        run: cargo build-sbf
